CREATE TABLE DEPT_TEMP2
AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'; -- UPDATE문으로 LOC열 데이터 전체 수정하기

ROLLBACK; -- 수정한 내용을 되돌리고 싶을때 ROLLBACK명령문 사용

UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE'
,LOC = 'SEOUL' WHERE DEPTNO = 40; -- UPDATE문에 WHERE절과 조건식 사용하여 테이블 데이터중 일부만 수정하기

SELECT * FROM EMP_TEMP;
UPDATE EMP_TEMP SET COMM = 50 WHERE SAL >=2500;


UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT
WHERE DEPTNO = 40)
WHERE DEPTNO = 40; -- 서브쿼리로 데이터 일부분 수정하기

UPDATE DEPT_TEMP2
SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO = 40)
,LOC = (SELECT LOC FROM DEPT WHERE DEPTNO = 40) WHERE DEPTNO = 40; -- 서브쿼로리 열 하나하나 수정하기

UPDATE DEPT_TEMP2
SET LOC = 'SEOUL' WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME = 'OPERATIONS'); -- UPDATE문 WHERE절에 서브쿼리 사용하기
SELECT * FROM DEPT_TEMP2;

CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2 WHERE JOB = 'MANAGER';
SELECT * FROM EMP_TEMP2;
ROLLBACK;

DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
FROM EMP_TEMP2 E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 3
AND DEPTNO = 30); -- WHERE 절에 서브쿼리를 사용하여 데이터 일부 삭제하기
DELETE FROM EMP_TEMP2
WHERE EMPNO IN (SELECT E.EMPNO
FROM EMP_TEMP2 E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE = 3
AND DEPTNO = 30);

DELETE FROM EMP_TEMP WHERE SAL >= 3000;
SELECT * FROM EMP_TEMP;

DELETE FROM EMP_TEMP2;
SELECT * FROM EMP_TEMP2; -- 데이터 전체 삭제하기

CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL'); -- INSERT, UPDATE, DELETE전에 SELECT로 확인하는 습관기르기
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40; -- 테이블 데이터 입력, 수정, 삭제하기
DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';
COMMIT;
ROLLBACK;

SELECT * FROM DEPT_TCL;
SELECT * FROM DEPT_TCL;
SELECT * FROM DEPT_TCL WHERE DEPTNO =50;
DELETE FROM DEPT_TCL WHERE DEPTNO =50;
COMMIT;

UPDATE DEPT_TCL SET LOC='SEOUL'
WHERE DEPTNO = 30;

ROLLBACK;

UPDATE DEPT_TCL SET LOC = 'SEOUL'
WHERE DEPTNO = 30;
SELECT * FROM DEPT_TCL;

CREATE TABLE EMP_DDL(
EMPNO NUMBER(4) -- 열 이름 자료형(저장할 데이터 길이)
,ENAME VARCHAR2(10)
,JOB VARCHAR2(9)
,MGR NUMBER(4)
,HIREDATE DATE
, SAL NUMBER(7,2)
, COMM NUMBER(7,2)
, DEPTNO NUMBER(2) );
DESC EMP_DDL; -- 모든 열의 각 자료형을 정의해서 테이블 생성하기

SELECT * FROM EMP_DDL;

CREATE TABLE DEPT_DDL AS SELECT * FROM DEPT;

DESC DEPT_DDL;
SELECT * FROM DEPT_DDL;

CREATE TABLE EMP_DDL_30
AS SELECT * FROM EMP
WHERE DEPTNO = 30;
SELECT * FROM EMP_DDL_30;

CREATE TABLE EMPDEPT_DDL
AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE
, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D WHERE 1 <> 1;

SELECT * FROM EMPDEPT_DDL;

CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;
SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20); -- ALTER명령어로 HP열 추가하기

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL; -- ALTER명령어로 HP칼럼 이름을 TEL로 변경하기
SELECT * FROM EMP_ALTER; 

ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5);
DESC EMP_ALTER;

ALTER TABLE EMP_ALTER DROP COLUMN TEL;
SELECT * FROM EMP_ALTER;

RENAME EMP_ALTER TO EMP_RENAME;
DESC EMP_ALTER;

TRUNCATE TABLE EMP_RENAME; -- 테이블의 데이터를 삭제하는 TRUNCATE
SELECT * FROM EMP_RENAME; -- ROLLBACK안되니 주의

DROP TABLE EMP_RENAME;
DESC EMP_RENAME;